//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSICLookup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSICLookup()
        {
            this.tblSites = new HashSet<tblSite>();
        }
    
        public string Division { get; set; }
        public int MajorGroup { get; set; }
        public int IndustryGroup { get; set; }
        public int SIC { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSite> tblSites { get; set; }
    }
}
